#!/bin/sh

SWARM_API_IP_TMP=$SWARM_API_IP
SWARM_NODE_IP_TMP=$SWARM_NODE_IP
API_IP_ADDRESS_TMP=$API_IP_ADDRESS
ETCD_SERVER_IP_TMP=$ETCD_SERVER_IP

cat > /etc/sysconfig/heat-params << END_SERVICE
WAIT_HANDLE="$WAIT_HANDLE"
ETCD_DISCOVERY_URL="$ETCD_DISCOVERY_URL"
DOCKER_VOLUME="$DOCKER_VOLUME"
HTTP_PROXY="$HTTP_PROXY"
HTTPS_PROXY="$HTTPS_PROXY"
NO_PROXY="$NO_PROXY"
SWARM_API_IP="${SWARM_API_IP_TMP:-$(hostname -I | cut -d' ' -f1)}"
SWARM_NODE_IP="${SWARM_NODE_IP_TMP:-$(hostname -I | cut -d' ' -f1)}"
BAY_UUID="$BAY_UUID"
USER_TOKEN="$USER_TOKEN"
MAGNUM_URL="$MAGNUM_URL"
TLS_DISABLED="$TLS_DISABLED"
NETWORK_DRIVER="$NETWORK_DRIVER"
FLANNEL_NETWORK_CIDR="$FLANNEL_NETWORK_CIDR"
FLANNEL_NETWORK_SUBNETLEN="$FLANNEL_NETWORK_SUBNETLEN"
FLANNEL_USE_VXLAN="$FLANNEL_USE_VXLAN"
ETCD_SERVER_IP="${ETCD_SERVER_IP_TMP:-$(hostname -I | cut -d' ' -f1)}"
API_IP_ADDRESS="${API_IP_ADDRESS_TMP:-$(hostname -I | cut -d' ' -f1)}"
SWARM_VERSION="$SWARM_VERSION"
AGENT_WAIT_HANDLE="$AGENT_WAIT_HANDLE"
END_SERVICE

chown root:root /etc/sysconfig/heat-params
chmod 644 /etc/sysconfig/heat-params

